# Generated by Django 4.2 on 2023-04-30 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=80)),
                ('last_name', models.CharField(max_length=80)),
                # ('email', models.EmailField()),
                ('date', models.DateField()),
                ('occupation', models.CharField(max_length=80)),
            ],
        ),
    ]
